#!/usr/bin/python

codes = [
        ('lit', 'L'),
        ('lit', 'o'),
        ('lit', 'r'),
        ('lit', 'e'),
        ('lit', 'm'),
        ('lit', ' '),
        ('lit', 'i'),
        ('lit', 'p'),
        ('lit', 's'),
        ('lit', 'u'),
        ('lit', 'm'),
        ('lit', ' '),
        ('lit', 'd'),
        ('lit', 'o'),
        ('lit', 'l'),
        ('lit', 'o'),
        ('lit', 'r'),
        ('lit', ' '),
        ('lit', 's'),
        ('lit', 'i'),
        ('lit', 't'),
        ('lit', ' '),
        ('lit', 'a'),
        ('lit', 'm'),
        ('lit', 'e'),
        ('lit', 't'),
        ('lit', ','),
        ('lit', ' '),
        ('lit', 'c'),
        ('lit', 'o'),
        ('lit', 'n'),
        ('lit', 's'),
        ('lit', 'e'),
        ('lit', 'c'),
        ('lit', 't'),
        ('lit', 'e'),
        ('lit', 't'),
        ('lit', 'u'),
        ('lit', 'r'),
        ('lit', ' '),
        ('lit', 'a'),
        ('lit', 'd'),
        ('lit', 'i'),
        ('lit', 'p'),
        ('lit', 'i'),
        ('lit', 's'),
        ('lit', 'c'),
        ('lit', 'i'),
        ('lit', 'n'),
        ('lit', 'g'),
        ('lit', ' '),
        ('lit', 'e'),
        ('lit', 'l'),
        ('lit', 'i'),
        ('lit', 't'),
        ('lit', '.'),
        ('lit', ' '),
        ('lit', 'D'),
        ('lit', 'o'),
        ('lit', 'n'),
        ('lit', 'e'),
        ('lit', 'c'),
        ('lit', ' '),
        ('lit', 'a'),
        ('lit', ' '),
        ('lit', 'd'),
        ('lit', 'i'),
        ('lit', 'a'),
        ('lit', 'm'),
        ('lit', ' '),
        ('lit', 'l'),
        ('ld', 3, 39),
        ('lit', 'u'),
        ('lit', 's'),
        ('lit', '.'),
        ('lit', ' '),
        ('lit', 'S'),
        ('lit', 'e'),
        ('lit', 'd'),
        ('ld', 9, 64),
        ('ld', 7, 85),
        ('lit', 'm'),
        ('lit', 'a'),
        ('lit', 'u'),
        ('lit', 'r'),
        ('lit', 'i'),
        ('ld', 3, 27),
        ('lit', 'M'),
        ('lit', 'a'),
        ('lit', 'e'),
        ('lit', 'c'),
        ('lit', 'e'),
        ('lit', 'n'),
        ('lit', 'a'),
        ('lit', 's'),
        ('ld', 4, 86),
        ('lit', 'g'),
        ('lit', 'u'),
        ('lit', 'e'),
        ('lit', ' '),
        ('lit', 'l'),
        ('lit', 'i'),
        ('lit', 'g'),
        ('lit', 'u'),
        ('lit', 'l'),
        ('lit', 'a'),
        ('lit', ' '),
        ('lit', 'a'),
        ('lit', 'c'),
        ('lit', ' '),
        ('lit', 'q'),
        ('lit', 'u'),
        ('ld', 3, 66),
        ('lit', 'v'),
        ('lit', 'i'),
        ('lit', 'v'),
        ('lit', 'e'),
        ('lit', 'r'),
        ('lit', 'r'),
        ('lit', 'a'),
        ('lit', ' '),
        ('ld', 4, 85),
        ('ld', 13, 120),
        ('lit', 'n'),
        ('lit', 't'),
        ('lit', 'e'),
        ('lit', ' '),
        ('lit', 'h'),
        ('lit', 'e'),
        ('lit', 'n'),
        ('lit', 'd'),
        ('lit', 'r'),
        ('lit', 'e'),
        ('lit', 'r'),
        ('ld', 10, 119),
        ('lit', 'e'),
        ('lit', 't'),
        ('lit', ' '),
        ('lit', 'm'),
        ('lit', 'o'),
        ('lit', 'l'),
        ('lit', 'l'),
        ('lit', 'i'),
        ('lit', 's'),
        ('ld', 6, 180),
        ('lit', '.'),
        ('lit', ' '),
        ('lit', 'P'),
        ('lit', 'r'),
        ('lit', 'a'),
        ('lit', 'e'),
        ('lit', 's'),
        ('lit', 'e'),
        ('lit', 'n'),
        ('lit', 't'),
        ('lit', ' '),
        ('ld', 3, 26),
        ('ld', 5, 146),
        ('lit', 'e'),
        ('lit', 'g'),
        ('ld', 3, 10),
        ('lit', 'l'),
        ('lit', 'i'),
        ('lit', 'b'),
        ('lit', 'e'),
        ('lit', 'r'),
        ('lit', 'o'),
        ('lit', ' '),
        ('ld', 3, 12),
        ('lit', 's'),
        ('lit', 't'),
        ('ld', 3, 122),
        ('lit', 'm'),
        ('lit', 'a'),
        ('lit', 't'),
        ('lit', 't'),
        ('ld', 3, 51),
        ('ld', 8, 225),
        ('ld', 3, 116),
        ('lit', 't'),
        ('lit', 'a'),
        ('lit', 'e'),
        ('lit', ' '),
        ('lit', 'a'),
        ('lit', 'u'),
        ('ld', 3, 143),
        ('lit', '.'),
        ('lit', ' '),
        ('lit', 'N'),
        ('ld', 3, 133),
        ('lit', 't'),
        ('lit', 'i'),
        ('lit', 'n'),
        ('lit', 'c'),
        ('lit', 'i'),
        ('lit', 'd'),
        ('lit', 'u'),
        ('ld', 3, 71),
        ('ld', 7, 165),
        ('lit', 'e'),
        ('lit', 'n'),
        ('lit', 'i'),
        ('lit', 'm'),
        ('lit', ','),
        ('lit', ' '),
        ('lit', 'u'),
        ('lit', 't'),
        ('lit', ' '),
        ('lit', 'p'),
        ('lit', 'o'),
        ('lit', 'r'),
        ('lit', 't'),
        ('lit', 'a'),
        ('lit', ' '),
        ('ld', 3, 287),
        ('ld', 3, 301),
        ('lit', 'l'),
        ('lit', 'a'),
        ('ld', 3, 263),
        ('lit', 'i'),
        ('lit', 'a'),
        ('ld', 12, 167),
        ('ld', 8, 271),
        ('ld', 3, 42),
        ('ld', 7, 116),
        ('lit', 's'),
        ('ld', 3, 266),
        ('lit', 'a'),
        ('lit', 'r'),
        ('lit', 'c'),
        ('lit', 'u'),
        ('lit', ' '),
        ('lit', 'v'),
        ('lit', 'e'),
        ('lit', 'h'),
        ('lit', 'i'),
        ('lit', 'c'),
        ('ld', 4, 234),
        ('lit', 'u'),
        ('lit', 'l'),
        ('lit', 't'),
        ('lit', 'r'),
        ('lit', 'i'),
        ('lit', 'c'),
        ('lit', 'i'),
        ('lit', 'e'),
        ('lit', 's'),
        ('ld', 3, 309),
        ('lit', 'n'),
        ('lit', 'o'),
        ('lit', 'n'),
        ('lit', ' '),
        ('lit', 't'),
        ('ld', 3, 83),
        ('lit', 'o'),
        ('lit', 'r'),
        ('lit', '.'),
        ('lit', ' '),
        ('lit', 'L'),
        ('ld', 56, 386),
        ('lit', 'A'),
        ('lit', 'e'),
        ('lit', 'n'),
        ('lit', 'e'),
        ('lit', 'a'),
        ('lit', 'n'),
        ('ld', 4, 158),
        ('lit', 'g'),
        ('lit', 'r'),
        ('lit', 'a'),
        ('lit', 'v'),
        ('lit', 'i'),
        ('lit', 'd'),
        ('ld', 7, 160),
        ('lit', '.'),
        ('lit', ' '),
        ('lit', 'U'),
        ('lit', 't'),
        ('lit', ' '),
        ('ld', 3, 435),
        ('ld', 3, 431),
        ('lit', ' '),
        ('lit', 'f'),
        ('ld', 3, 428),
        ('lit', 's'),
        ('lit', ','),
        ('lit', ' '),
        ('lit', 'p'),
        ('lit', 'u'),
        ('lit', 'l'),
        ('lit', 'v'),
        ('lit', 'i'),
        ('lit', 'n'),
        ('lit', 'a'),
        ('ld', 3, 454),
        ('lit', ' '),
        ('lit', 's'),
        ('lit', 'e'),
        ('lit', 'm'),
        ('lit', 'p'),
        ('lit', 'e'),
        ('ld', 3, 485),
        ('lit', 'e'),
        ('lit', 'd'),
        ('lit', ','),
        ('ld', 12, 468),
        ('lit', 'i'),
        ('lit', 'd'),
        ('ld', 9, 330),
        ('lit', 'e'),
        ('lit', 'l'),
        ('lit', 'l'),
        ('ld', 3, 329),
        ('lit', 'e'),
        ('lit', 's'),
        ('lit', 'q'),
        ('ld', 3, 421),
        ('lit', 'a'),
        ('lit', 'u'),
        ('lit', 'c'),
        ('ld', 3, 164),
        ('lit', ' '),
        ('lit', 'n'),
        ('lit', 'i'),
        ('lit', 's'),
        ('lit', 'i'),
        ('lit', ' '),
        ('ld', 3, 35),
        ('lit', 'm'),
        ('lit', 'a'),
        ('lit', 'g'),
        ('lit', 'n'),
        ('ld', 7, 248),
        ('ld', 3, 437),
        ('lit', 't'),
        ('lit', ' '),
        ('lit', 's'),
        ('lit', 'a'),
        ('lit', 'g'),
        ('lit', 'i'),
        ('ld', 4, 339),
        ('lit', '.'),
        ('lit', ' '),
        ('lit', 'C'),
        ('lit', 'u'),
        ('lit', 'r'),
        ('lit', 'a'),
        ('lit', 'b'),
        ('lit', 'i'),
        ('ld', 4, 553),
        ('lit', 'd'),
        ('lit', 'a'),
        ('lit', 'p'),
        ('lit', 'i'),
        ('lit', 'b'),
        ('lit', 'u'),
        ('lit', 's'),
        ('lit', ' '),
        ('ld', 4, 315),
        ('ld', 10, 363),
        ('ld', 4, 564),
        ('lit', ' '),
        ('lit', 'p'),
        ('lit', 'h'),
        ('lit', 'a'),
        ('lit', 'r'),
        ('lit', 'e'),
        ('lit', 't'),
        ('ld', 3, 485),
        ('ld', 10, 360),
        ('lit', 'f'),
        ('lit', 'e'),
        ('lit', 'u'),
        ('lit', 'g'),
        ('lit', 'i'),
        ('ld', 3, 74),
        ('ld', 3, 98),
        ('lit', 'l'),
        ('lit', ' '),
        ('lit', 'i'),
        ('ld', 4, 155),
        ('lit', 'd'),
        ('lit', 'i'),
        ('lit', 'e'),
        ('ld', 3, 606),
        ('ld', 3, 195),
        ('ld', 3, 387),
        ('lit', 'v'),
        ('lit', 'a'),
        ('ld', 5, 484),
        ('ld', 7, 339),
        ('lit', 'i'),
        ('ld', 3, 236),
        ('lit', 'r'),
        ('ld', 3, 128),
        ('ld', 6, 329),
        ('ld', 4, 328),
        ('lit', 'c'),
        ('lit', 'c'),
        ('lit', 'u'),
        ('lit', 'm'),
        ('lit', 's'),
        ('lit', 'a'),
        ('lit', 'n'),
        ('ld', 8, 382),
        ('ld', 4, 372),
        ('lit', 'o'),
        ('lit', 'd'),
        ('lit', 'i'),
        ('ld', 3, 497),
        ('lit', 'r'),
        ('lit', 'o'),
        ('ld', 3, 148),
        ('ld', 6, 674),
        ('ld', 8, 601),
        ('lit', 'm'),
        ('lit', 'i'),
        ('ld', 3, 617),
        ('ld', 3, 275),
        ('ld', 5, 622),
        ('ld', 10, 273),
        ('ld', 3, 585),
        ('lit', 'a'),
        ('lit', 'l'),
        ('lit', 'e'),
        ('lit', 's'),
        ('lit', 'u'),
        ('lit', 'a'),
        ('ld', 3, 319),
        ('ld', 5, 432),
        ('lit', 'r'),
        ('lit', 'h'),
        ('lit', 'o'),
        ('lit', 'n'),
        ('lit', 'c'),
        ('ld', 4, 716),
        ('lit', 'C'),
        ('ld', 3, 786),
        ('lit', 's'),
        ('lit', 'o'),
        ('lit', 'c'),
        ('lit', 'i'),
        ('ld', 3, 52),
        ('lit', 'n'),
        ('lit', 'a'),
        ('lit', 't'),
        ('lit', 'o'),
        ('ld', 4, 271),
        ('lit', 'p'),
        ('ld', 3, 705),
        ('lit', 't'),
        ('ld', 6, 222),
        ('ld', 4, 56),
        ('lit', 'g'),
        ('ld', 3, 182),
        ('ld', 3, 622),
        ('lit', 's'),
        ('lit', ' '),
        ('lit', 'p'),
        ('lit', 'a'),
        ('lit', 'r'),
        ('ld', 3, 251),
        ('lit', 'i'),
        ('ld', 4, 640),
        ('lit', 'm'),
        ('lit', 'o'),
        ('ld', 4, 316),
        ('lit', ','),
        ('ld', 3, 51),
        ('lit', 's'),
        ('lit', 'c'),
        ('ld', 5, 825),
        ('lit', 'r'),
        ('lit', 'i'),
        ('lit', 'd'),
        ('ld', 4, 512),
        ('ld', 3, 274),
        ('lit', 'm'),
        ('ld', 4, 86),
        ('lit', 'I'),
        ('lit', 'n'),
        ('lit', ' '),
        ('lit', 'r'),
        ('lit', 'u'),
        ('lit', 't'),
        ('lit', 'r'),
        ('ld', 3, 92),
        ('ld', 8, 190),
        ('ld', 10, 537),
        ('ld', 4, 805),
        ('ld', 4, 813),
        ('ld', 7, 665),
        ('ld', 5, 374),
        ('ld', 4, 358),
        ('ld', 3, 628),
        ('lit', 'f'),
        ('ld', 3, 628),
        ('ld', 3, 459),
        ('ld', 3, 28),
        ('ld', 7, 449),
        ('ld', 3, 824),
        ('ld', 3, 272),
        ('ld', 3, 728),
        ('lit', '.'),
]

output = []
for code in codes:
    if code[0] == 'lit':
        output.append(code[1])
    elif code[0] == 'ld':
        length = code[1]
        distance = code[2]
        print ""
        print "Length: ", code[1], " DIstance: ", code[2]
        print "".join(output)
        print "{:s}{:s}".format(" " * (len(output) - distance), "^" * length)
        for i in range(length):
            output.append(output[-distance])
        print "".join(output)
        print ""
    else:
        raise Exception("invalid code")

print ''.join(output)
